service: aws-nodejs # NOTE: update this with your service nam

plugins:
  - serverless-pseudo-parameters

provider:
  name: aws
  runtime: nodejs12.x
  region: us-west-2

functions:
  get-index:
    handler: functions/get-index.handler
    events:
      - http:
          path: /
          method: get